### ISSUE TITLE
Cannot set property __awaiter of [object Module] which has only a getter

### ISSUE THREAD

**Issue by lentschi** [itaysabato/cancelable-awaiter#1] opened 2019-12-07 10:52 UTC
Hi @itaysabato 

Thanks a lot for your lib - It would be great to be able to use cancelable awaiters!

I'm just encountering an error (at runtime!) when trying to do so: `Cannot set property __awaiter of [object Module] which has only a getter`

I'm using a blank new angular project and added this at the top of the entrypoint (`main.ts`) like it says in your README:

```typescript
import * as tslib from 'tslib';
import Bluebird from 'bluebird';
import * as awaiter from 'cancelable-awaiter';

Bluebird.config({cancellation: true});
(tslib as any).__awaiter = awaiter; // <- This is throwing the error
```

I tried updating `tslib` to the newest version `1.10.0`, but that didn't help. Here's my tsconfig, in which I added `"importHelpers": true` as it says in your README:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

Do you have any ideas what I could be doing wrong or could you maybe provide a sample project consuming your lib?

**Comment by itaysabato** [comment] 2019-12-08 15:00
@yigaldviri Do you have a workaround for this?

**Comment by yigaldviri** [comment] 2019-12-08 15:25
We are setting it this way:
```js
import bluebird from 'bluebird-global';
import BluebirdPromise from "bluebird";
import awaiter from "cancelable-awaiter";

BluebirdPromise.config({
    cancellation: true,
    longStackTraces: false,
});

if (global) {
    global.Promise = BluebirdPromise;
    global.Bluebird = BluebirdPromise;
    tslib.__assign(global, tslib, {__awaiter: awaiter});
}
```
Maybe setting it this way will help

**Comment by lentschi** [comment] 2019-12-09 19:39
@yigaldviri @itaysabato Thanks for your quick responses! Unfortunately it won't work with the alternate assign call.
Obviously where I go wrong is putting the override into angular's `main.ts`. This is code, that's executed in the browser and that cannot work (It's in the browser where I get the error - not in the build process).

It would need a way of transpiling `await` statements differently before they arrive at the browser instead. I guess I'll have to do some more research about webpack to see if that's possible at all.
Running a test app using `cancelable-awaiter` with `ts-node` worked fine for me, so frontend usage is probably just out of the scope of this lib...?
If so, sorry for bothering you and feel free to close this issue!

**Comment by itaysabato** [comment] 2019-12-09 21:00
@lentschi Try setting in the tsconfig `"noEmitHelpers": true` and `"importHelpers": false`

Then you need to place all the helpers on the window yourself for TypeScript to use:
`tslib.__assign(self, tslib, {__awaiter: awaiter});`

This avoids the module system limitation.

Sorry, the docs may be out of date.

**Comment by lentschi** [comment] 2019-12-11 12:45
Hi @itaysabato 
If I do that, I get the error `__decorate is not defined` for the first occurrence of a typescript decorator. For which the solution seems to be setting `noEmitHelpers` to `false` (see https://github.com/inversify/InversifyJS/issues/808 ). If I do that it actually starts to run, however async functions still don't return Bluebird promises.

But interestingly, while debugging I found out that I don't get a normal ES6 Promise either. What I get is a so called ZoneAwarePromise (see https://stackoverflow.com/questions/52391762/what-is-a-zoneawarepromise ) So probably this is an angular specific question, because it seems they are already succeeding in modifying an async function's return type. I'll keep you posted, if I find out more!

**Comment by lentschi** [comment] 2019-12-16 20:39
@itaysabato I solved part one of the problem here: https://stackoverflow.com/questions/59343212/how-to-enable-zone-aware-bluebird-promises-in-angular-8/59363827#59363827

But like I remarked in my answer there, without something like `cancelable-awaiter` for angular, cancelling promises returned by async functions will not call the `onCancel` callback of the wrapped bluebird promise.

**Comment by itaysabato** [comment] 2019-12-17 07:53
@lentschi So if I understand correctly, the problem is that Angular is already changing the native Promise implementation with `ZoneAwarePromise` so they cannot be replaced with Bluebird promises?

And there is no way to opt out of this?

**Comment by lentschi** [comment] 2019-12-17 19:36
@itaysabato No that's the part I *did* figure out (see the Stackoverflow-Link I shared in my previous comment)

I just still don't manage to include `cancelable-awaiter` in my angular project. And without it I do get Bluebird promises, but they don't magically hand their `onCancel` callbacks down the async method chain.

To illustrate a working and a failing sample:

## Failing sample (angular)
https://stackblitz.com/edit/angular-bluebird-promises?embed=1&file=src%2Fapp%2Fapp.component.ts&devtoolsheight=50 

This outputs on the browser console (incorrect!):

```
Started
Timeout1!
Timeout2!
Trying to cancel...
Promise finally reached
Timeout3!
```
**Note** that I couldn't even *try* to activate `cancelable-awaiter` on StackBlitz, because it doesn't like that. When I run the same code locally (with `npm run start`), I can, but either get errors or the same failing output as above (depending on my `tsconfig.json`).
Also note that hot reloading on StackBlitz won't work with this zone.js hack (Locally it works fine though) - you'll have to hit the reload button in the preview, if you try to change anything.

## Working sample (ts-node, but otherwise same code!)

```bash
git clone https://github.com/lentschi/cancelable-ts-node-test.git
cd cancelable-ts-node-test/
npm i
ts-node main.ts
```

This prints:

```
Started
Timeout1!
Timeout2!
Trying to cancel...
Canceled3
Promise finally reached
```

...like it *should* :wink:  ( `onCancel` callbacks magically handed down the async method chain by your lib)

**Comment by lentschi** [comment] 2019-12-23 18:42
Just found out two more things:

1. Bundling manually with a [basic webpack config](https://webpack.js.org/guides/typescript/) this works exactly as it's been described in your `README`.
2. If I build with angular (which uses webpack internally) it still doesn't. Apparently something in angular's webpack config causes this. tslib.__awaiter is only a setter. **But** if I go and manually edit `node_modules/tslib/tslib.es6.js` to include your awaiter instead of the original one, it works - even with angular :fireworks: . So maybe the solution is to simply fork tslib and provide it under the same name (e.g. by using an additional private npm repository.)

**Comment by lentschi** [comment] 2019-12-24 21:44
I made it work by including a forked tslib with your awaiter in my project. Here's a sample:

```bash
git clone https://github.com/lentschi/cancelable-awaiter-angular.git
cd cancelable-awaiter-angular
npm i
npm run start
```

(Unfortunately I can't provide a StackBlitz for this as it doesn't support `tsconfig.json`)

@itaysabato Unless you have any suggestions on how to better override tslib, I think you can close this issue now. Thanks for all your help! :smiley:

**Comment by itaysabato** [comment] 2019-12-29 14:13
@lentschi I'm glad you figured it out :)
Closing for now.

**Closed as completed by itaysabato** 2019-12-29 14:13 UTC

**Comment by Jazzepi** [comment] 2020-02-14 02:46
I think I understand the underlying problem. In the move from Webpack version 3->4 they changed the way they export properties. Instead of just putting them on an object (which would allow you to overwrite them) they hide them behind a getter. Because there's no setter it's effectively immutable.

https://github.com/webpack/webpack/issues/6979

So this

`(tslib as any).__awaiter = awaiter;`

Stops working in webpack 4+

Someone in the same thread wrote a plugin for webpack. I have no idea how it works, and this is a bit too far down the rabbit hole for me to go at this point as much as I like this project.

https://github.com/webpack/webpack/issues/6979#issuecomment-389220417

**Comment by itaysabato** [comment] 2020-03-31 16:59
@Jazzepi I think this is just Webpack adhering to the standard of how ESM should work.
The implication is that `tslib` should be included differently - as described [here](https://github.com/itaysabato/cancelable-awaiter/issues/1#issuecomment-563436449)
